// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrkborkeiqcuarqtzpdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZya2JvcmtlaXFjdWFycXR6cGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzkzNDAsImV4cCI6MjA2MjkxNTM0MH0.GA-mU5J2RQmsuYdaCkaNXuzZmfRzyJRv70wX4064sGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);